name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK 21 and cache Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Clean & build debug
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: app/build/outputs/apk/**/*.apk